### Verify Email
POST http://localhost:62641/tech/api/v2/auth/verify/email
Content-Type: application/json

{
    "email": "foobar@example.com"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
