### Check if access token is valid
GET http://{{userHost}}/{{httpBase}}/auth/check
x-access-token: {{accessToken}}

### Refresh access token
GET http://{{userHost}}/{{httpBase}}/auth/refresh
x-refresh-token: {{refreshToken}}

### Verify email
POST http://{{userHost}}/{{httpBase}}/auth/verify/email
Content-Type: application/json

{
    "email": "myname@example.com"
}

### Login with email and code
POST http://{{userHost}}/{{httpBase}}/auth/login/email
Content-Type: application/json

{
    "email": "myname@example.com",
    "code": "1A2B3C4D"
}

### Login with email and password
POST http://{{userHost}}/{{httpBase}}/auth/login/email
Content-Type: application/json

{
    "email": "myname@example.com",
    "password": "password"
}

### Reset password with email and code
PUT http://{{userHost}}/{{httpBase}}/auth/reset/email
Content-Type: application/json

{
    "email": "myname@example.com",
    "code": "1A2B3C4D",
    "newPassword": "password"
}

### Migrate email with access token and code
PUT http://{{userHost}}/{{httpBase}}/auth/migrate/email
x-access-token: {{accessToken}}
Content-Type: application/json

{
    "newEmail": "myname@example.com",
    "code": "1A2B3C4D"
}
