/**
 *
 *  Removed.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Removed.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::techluster;

const std::string Removed::Cols::_id = "id";
const std::string Removed::Cols::_username = "username";
const std::string Removed::Cols::_motto = "motto";
const std::string Removed::Cols::_region = "region";
const std::string Removed::Cols::_avatar = "avatar";
const std::string Removed::Cols::_avatar_hash = "avatar_hash";
const std::string Removed::Cols::_avatar_frame = "avatar_frame";
const std::string Removed::Cols::_clan = "clan";
const std::string Removed::Cols::_permission = "permission";
const std::string Removed::Cols::_password = "password";
const std::string Removed::Cols::_email = "email";
const std::string Removed::Cols::_data = "data";
const std::string Removed::Cols::_timestamp = "timestamp";
const std::string Removed::Cols::_recoverable = "recoverable";
const std::string Removed::primaryKeyName = "id";
const bool Removed::hasPrimaryKey = true;
const std::string Removed::tableName = "removed";

const std::vector<typename Removed::MetaData> Removed::metaData_ = {
        {"id",           "int64_t",         "bigint",                      8, 0, 1, 1},
        {"username",     "std::string",     "text",                        0, 0, 0, 0},
        {"motto",        "std::string",     "text",                        0, 0, 0, 0},
        {"region",       "int32_t",         "integer",                     4, 0, 0, 0},
        {"avatar",       "std::string",     "text",                        0, 0, 0, 0},
        {"avatar_hash",  "std::string",     "text",                        0, 0, 0, 0},
        {"avatar_frame", "int32_t",         "integer",                     4, 0, 0, 0},
        {"clan",         "std::string",     "text",                        0, 0, 0, 0},
        {"permission",   "std::string",     "USER-DEFINED",                0, 0, 0, 0},
        {"password",     "std::string",     "text",                        0, 0, 0, 0},
        {"email",        "std::string",     "text",                        0, 0, 0, 0},
        {"data",         "std::string",     "text",                        0, 0, 0, 1},
        {"timestamp",    "::trantor::Date", "timestamp without time zone", 0, 0, 0, 1},
        {"recoverable",  "bool",            "boolean",                     1, 0, 0, 1}
};

const std::string &Removed::getColumnName(size_t index) noexcept(false) {
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}

Removed::Removed(const Row &r, const ssize_t indexOffset) noexcept {
    if (indexOffset < 0) {
        if (!r["id"].isNull()) {
            id_ = std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if (!r["username"].isNull()) {
            username_ = std::make_shared<std::string>(r["username"].as<std::string>());
        }
        if (!r["motto"].isNull()) {
            motto_ = std::make_shared<std::string>(r["motto"].as<std::string>());
        }
        if (!r["region"].isNull()) {
            region_ = std::make_shared<int32_t>(r["region"].as<int32_t>());
        }
        if (!r["avatar"].isNull()) {
            avatar_ = std::make_shared<std::string>(r["avatar"].as<std::string>());
        }
        if (!r["avatar_hash"].isNull()) {
            avatarHash_ = std::make_shared<std::string>(r["avatar_hash"].as<std::string>());
        }
        if (!r["avatar_frame"].isNull()) {
            avatarFrame_ = std::make_shared<int32_t>(r["avatar_frame"].as<int32_t>());
        }
        if (!r["clan"].isNull()) {
            clan_ = std::make_shared<std::string>(r["clan"].as<std::string>());
        }
        if (!r["permission"].isNull()) {
            permission_ = std::make_shared<std::string>(r["permission"].as<std::string>());
        }
        if (!r["password"].isNull()) {
            password_ = std::make_shared<std::string>(r["password"].as<std::string>());
        }
        if (!r["email"].isNull()) {
            email_ = std::make_shared<std::string>(r["email"].as<std::string>());
        }
        if (!r["data"].isNull()) {
            data_ = std::make_shared<std::string>(r["data"].as<std::string>());
        }
        if (!r["timestamp"].isNull()) {
            auto timeStr = r["timestamp"].as<std::string>();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if (p) {
                if (*p == '.') {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6) {
                        decimals += "0";
                    }
                    decimalNum = (size_t) atol(decimals.c_str());
                }
                timestamp_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
        if (!r["recoverable"].isNull()) {
            recoverable_ = std::make_shared<bool>(r["recoverable"].as<bool>());
        }
    } else {
        size_t offset = (size_t) indexOffset;
        if (offset + 14 > r.size()) {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if (!r[index].isNull()) {
            id_ = std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if (!r[index].isNull()) {
            username_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if (!r[index].isNull()) {
            motto_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if (!r[index].isNull()) {
            region_ = std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 4;
        if (!r[index].isNull()) {
            avatar_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if (!r[index].isNull()) {
            avatarHash_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if (!r[index].isNull()) {
            avatarFrame_ = std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 7;
        if (!r[index].isNull()) {
            clan_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if (!r[index].isNull()) {
            permission_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 9;
        if (!r[index].isNull()) {
            password_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 10;
        if (!r[index].isNull()) {
            email_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 11;
        if (!r[index].isNull()) {
            data_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 12;
        if (!r[index].isNull()) {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if (p) {
                if (*p == '.') {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6) {
                        decimals += "0";
                    }
                    decimalNum = (size_t) atol(decimals.c_str());
                }
                timestamp_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
        index = offset + 13;
        if (!r[index].isNull()) {
            recoverable_ = std::make_shared<bool>(r[index].as<bool>());
        }
    }

}

Removed::Removed(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false) {
    if (pMasqueradingVector.size() != 14) {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
        dirtyFlag_[0] = true;
        if (!pJson[pMasqueradingVector[0]].isNull()) {
            id_ = std::make_shared<int64_t>((int64_t) pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
        dirtyFlag_[1] = true;
        if (!pJson[pMasqueradingVector[1]].isNull()) {
            username_ = std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
        dirtyFlag_[2] = true;
        if (!pJson[pMasqueradingVector[2]].isNull()) {
            motto_ = std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
        dirtyFlag_[3] = true;
        if (!pJson[pMasqueradingVector[3]].isNull()) {
            region_ = std::make_shared<int32_t>((int32_t) pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
        dirtyFlag_[4] = true;
        if (!pJson[pMasqueradingVector[4]].isNull()) {
            avatar_ = std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5])) {
        dirtyFlag_[5] = true;
        if (!pJson[pMasqueradingVector[5]].isNull()) {
            avatarHash_ = std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6])) {
        dirtyFlag_[6] = true;
        if (!pJson[pMasqueradingVector[6]].isNull()) {
            avatarFrame_ = std::make_shared<int32_t>((int32_t) pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7])) {
        dirtyFlag_[7] = true;
        if (!pJson[pMasqueradingVector[7]].isNull()) {
            clan_ = std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if (!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8])) {
        dirtyFlag_[8] = true;
        if (!pJson[pMasqueradingVector[8]].isNull()) {
            permission_ = std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if (!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9])) {
        dirtyFlag_[9] = true;
        if (!pJson[pMasqueradingVector[9]].isNull()) {
            password_ = std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if (!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10])) {
        dirtyFlag_[10] = true;
        if (!pJson[pMasqueradingVector[10]].isNull()) {
            email_ = std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if (!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11])) {
        dirtyFlag_[11] = true;
        if (!pJson[pMasqueradingVector[11]].isNull()) {
            data_ = std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if (!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12])) {
        dirtyFlag_[12] = true;
        if (!pJson[pMasqueradingVector[12]].isNull()) {
            auto timeStr = pJson[pMasqueradingVector[12]].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if (p) {
                if (*p == '.') {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6) {
                        decimals += "0";
                    }
                    decimalNum = (size_t) atol(decimals.c_str());
                }
                timestamp_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
    if (!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13])) {
        dirtyFlag_[13] = true;
        if (!pJson[pMasqueradingVector[13]].isNull()) {
            recoverable_ = std::make_shared<bool>(pJson[pMasqueradingVector[13]].asBool());
        }
    }
}

Removed::Removed(const Json::Value &pJson) noexcept(false) {
    if (pJson.isMember("id")) {
        dirtyFlag_[0] = true;
        if (!pJson["id"].isNull()) {
            id_ = std::make_shared<int64_t>((int64_t) pJson["id"].asInt64());
        }
    }
    if (pJson.isMember("username")) {
        dirtyFlag_[1] = true;
        if (!pJson["username"].isNull()) {
            username_ = std::make_shared<std::string>(pJson["username"].asString());
        }
    }
    if (pJson.isMember("motto")) {
        dirtyFlag_[2] = true;
        if (!pJson["motto"].isNull()) {
            motto_ = std::make_shared<std::string>(pJson["motto"].asString());
        }
    }
    if (pJson.isMember("region")) {
        dirtyFlag_[3] = true;
        if (!pJson["region"].isNull()) {
            region_ = std::make_shared<int32_t>((int32_t) pJson["region"].asInt64());
        }
    }
    if (pJson.isMember("avatar")) {
        dirtyFlag_[4] = true;
        if (!pJson["avatar"].isNull()) {
            avatar_ = std::make_shared<std::string>(pJson["avatar"].asString());
        }
    }
    if (pJson.isMember("avatar_hash")) {
        dirtyFlag_[5] = true;
        if (!pJson["avatar_hash"].isNull()) {
            avatarHash_ = std::make_shared<std::string>(pJson["avatar_hash"].asString());
        }
    }
    if (pJson.isMember("avatar_frame")) {
        dirtyFlag_[6] = true;
        if (!pJson["avatar_frame"].isNull()) {
            avatarFrame_ = std::make_shared<int32_t>((int32_t) pJson["avatar_frame"].asInt64());
        }
    }
    if (pJson.isMember("clan")) {
        dirtyFlag_[7] = true;
        if (!pJson["clan"].isNull()) {
            clan_ = std::make_shared<std::string>(pJson["clan"].asString());
        }
    }
    if (pJson.isMember("permission")) {
        dirtyFlag_[8] = true;
        if (!pJson["permission"].isNull()) {
            permission_ = std::make_shared<std::string>(pJson["permission"].asString());
        }
    }
    if (pJson.isMember("password")) {
        dirtyFlag_[9] = true;
        if (!pJson["password"].isNull()) {
            password_ = std::make_shared<std::string>(pJson["password"].asString());
        }
    }
    if (pJson.isMember("email")) {
        dirtyFlag_[10] = true;
        if (!pJson["email"].isNull()) {
            email_ = std::make_shared<std::string>(pJson["email"].asString());
        }
    }
    if (pJson.isMember("data")) {
        dirtyFlag_[11] = true;
        if (!pJson["data"].isNull()) {
            data_ = std::make_shared<std::string>(pJson["data"].asString());
        }
    }
    if (pJson.isMember("timestamp")) {
        dirtyFlag_[12] = true;
        if (!pJson["timestamp"].isNull()) {
            auto timeStr = pJson["timestamp"].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if (p) {
                if (*p == '.') {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6) {
                        decimals += "0";
                    }
                    decimalNum = (size_t) atol(decimals.c_str());
                }
                timestamp_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
    if (pJson.isMember("recoverable")) {
        dirtyFlag_[13] = true;
        if (!pJson["recoverable"].isNull()) {
            recoverable_ = std::make_shared<bool>(pJson["recoverable"].asBool());
        }
    }
}

void Removed::updateByMasqueradedJson(const Json::Value &pJson,
                                      const std::vector<std::string> &pMasqueradingVector) noexcept(false) {
    if (pMasqueradingVector.size() != 14) {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
        if (!pJson[pMasqueradingVector[0]].isNull()) {
            id_ = std::make_shared<int64_t>((int64_t) pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
        dirtyFlag_[1] = true;
        if (!pJson[pMasqueradingVector[1]].isNull()) {
            username_ = std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
        dirtyFlag_[2] = true;
        if (!pJson[pMasqueradingVector[2]].isNull()) {
            motto_ = std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
        dirtyFlag_[3] = true;
        if (!pJson[pMasqueradingVector[3]].isNull()) {
            region_ = std::make_shared<int32_t>((int32_t) pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
        dirtyFlag_[4] = true;
        if (!pJson[pMasqueradingVector[4]].isNull()) {
            avatar_ = std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5])) {
        dirtyFlag_[5] = true;
        if (!pJson[pMasqueradingVector[5]].isNull()) {
            avatarHash_ = std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6])) {
        dirtyFlag_[6] = true;
        if (!pJson[pMasqueradingVector[6]].isNull()) {
            avatarFrame_ = std::make_shared<int32_t>((int32_t) pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7])) {
        dirtyFlag_[7] = true;
        if (!pJson[pMasqueradingVector[7]].isNull()) {
            clan_ = std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if (!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8])) {
        dirtyFlag_[8] = true;
        if (!pJson[pMasqueradingVector[8]].isNull()) {
            permission_ = std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if (!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9])) {
        dirtyFlag_[9] = true;
        if (!pJson[pMasqueradingVector[9]].isNull()) {
            password_ = std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if (!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10])) {
        dirtyFlag_[10] = true;
        if (!pJson[pMasqueradingVector[10]].isNull()) {
            email_ = std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if (!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11])) {
        dirtyFlag_[11] = true;
        if (!pJson[pMasqueradingVector[11]].isNull()) {
            data_ = std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if (!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12])) {
        dirtyFlag_[12] = true;
        if (!pJson[pMasqueradingVector[12]].isNull()) {
            auto timeStr = pJson[pMasqueradingVector[12]].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if (p) {
                if (*p == '.') {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6) {
                        decimals += "0";
                    }
                    decimalNum = (size_t) atol(decimals.c_str());
                }
                timestamp_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
    if (!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13])) {
        dirtyFlag_[13] = true;
        if (!pJson[pMasqueradingVector[13]].isNull()) {
            recoverable_ = std::make_shared<bool>(pJson[pMasqueradingVector[13]].asBool());
        }
    }
}

void Removed::updateByJson(const Json::Value &pJson) noexcept(false) {
    if (pJson.isMember("id")) {
        if (!pJson["id"].isNull()) {
            id_ = std::make_shared<int64_t>((int64_t) pJson["id"].asInt64());
        }
    }
    if (pJson.isMember("username")) {
        dirtyFlag_[1] = true;
        if (!pJson["username"].isNull()) {
            username_ = std::make_shared<std::string>(pJson["username"].asString());
        }
    }
    if (pJson.isMember("motto")) {
        dirtyFlag_[2] = true;
        if (!pJson["motto"].isNull()) {
            motto_ = std::make_shared<std::string>(pJson["motto"].asString());
        }
    }
    if (pJson.isMember("region")) {
        dirtyFlag_[3] = true;
        if (!pJson["region"].isNull()) {
            region_ = std::make_shared<int32_t>((int32_t) pJson["region"].asInt64());
        }
    }
    if (pJson.isMember("avatar")) {
        dirtyFlag_[4] = true;
        if (!pJson["avatar"].isNull()) {
            avatar_ = std::make_shared<std::string>(pJson["avatar"].asString());
        }
    }
    if (pJson.isMember("avatar_hash")) {
        dirtyFlag_[5] = true;
        if (!pJson["avatar_hash"].isNull()) {
            avatarHash_ = std::make_shared<std::string>(pJson["avatar_hash"].asString());
        }
    }
    if (pJson.isMember("avatar_frame")) {
        dirtyFlag_[6] = true;
        if (!pJson["avatar_frame"].isNull()) {
            avatarFrame_ = std::make_shared<int32_t>((int32_t) pJson["avatar_frame"].asInt64());
        }
    }
    if (pJson.isMember("clan")) {
        dirtyFlag_[7] = true;
        if (!pJson["clan"].isNull()) {
            clan_ = std::make_shared<std::string>(pJson["clan"].asString());
        }
    }
    if (pJson.isMember("permission")) {
        dirtyFlag_[8] = true;
        if (!pJson["permission"].isNull()) {
            permission_ = std::make_shared<std::string>(pJson["permission"].asString());
        }
    }
    if (pJson.isMember("password")) {
        dirtyFlag_[9] = true;
        if (!pJson["password"].isNull()) {
            password_ = std::make_shared<std::string>(pJson["password"].asString());
        }
    }
    if (pJson.isMember("email")) {
        dirtyFlag_[10] = true;
        if (!pJson["email"].isNull()) {
            email_ = std::make_shared<std::string>(pJson["email"].asString());
        }
    }
    if (pJson.isMember("data")) {
        dirtyFlag_[11] = true;
        if (!pJson["data"].isNull()) {
            data_ = std::make_shared<std::string>(pJson["data"].asString());
        }
    }
    if (pJson.isMember("timestamp")) {
        dirtyFlag_[12] = true;
        if (!pJson["timestamp"].isNull()) {
            auto timeStr = pJson["timestamp"].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if (p) {
                if (*p == '.') {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6) {
                        decimals += "0";
                    }
                    decimalNum = (size_t) atol(decimals.c_str());
                }
                timestamp_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
    if (pJson.isMember("recoverable")) {
        dirtyFlag_[13] = true;
        if (!pJson["recoverable"].isNull()) {
            recoverable_ = std::make_shared<bool>(pJson["recoverable"].asBool());
        }
    }
}

const int64_t &Removed::getValueOfId() const noexcept {
    const static int64_t defaultValue = int64_t();
    if (id_)
        return *id_;
    return defaultValue;
}

const std::shared_ptr<int64_t> &Removed::getId() const noexcept {
    return id_;
}

void Removed::setId(const int64_t &pId) noexcept {
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}

const typename Removed::PrimaryKeyType &Removed::getPrimaryKey() const {
    assert(id_);
    return *id_;
}

const std::string &Removed::getValueOfUsername() const noexcept {
    const static std::string defaultValue = std::string();
    if (username_)
        return *username_;
    return defaultValue;
}

const std::shared_ptr<std::string> &Removed::getUsername() const noexcept {
    return username_;
}

void Removed::setUsername(const std::string &pUsername) noexcept {
    username_ = std::make_shared<std::string>(pUsername);
    dirtyFlag_[1] = true;
}

void Removed::setUsername(std::string &&pUsername) noexcept {
    username_ = std::make_shared<std::string>(std::move(pUsername));
    dirtyFlag_[1] = true;
}

void Removed::setUsernameToNull() noexcept {
    username_.reset();
    dirtyFlag_[1] = true;
}

const std::string &Removed::getValueOfMotto() const noexcept {
    const static std::string defaultValue = std::string();
    if (motto_)
        return *motto_;
    return defaultValue;
}

const std::shared_ptr<std::string> &Removed::getMotto() const noexcept {
    return motto_;
}

void Removed::setMotto(const std::string &pMotto) noexcept {
    motto_ = std::make_shared<std::string>(pMotto);
    dirtyFlag_[2] = true;
}

void Removed::setMotto(std::string &&pMotto) noexcept {
    motto_ = std::make_shared<std::string>(std::move(pMotto));
    dirtyFlag_[2] = true;
}

void Removed::setMottoToNull() noexcept {
    motto_.reset();
    dirtyFlag_[2] = true;
}

const int32_t &Removed::getValueOfRegion() const noexcept {
    const static int32_t defaultValue = int32_t();
    if (region_)
        return *region_;
    return defaultValue;
}

const std::shared_ptr<int32_t> &Removed::getRegion() const noexcept {
    return region_;
}

void Removed::setRegion(const int32_t &pRegion) noexcept {
    region_ = std::make_shared<int32_t>(pRegion);
    dirtyFlag_[3] = true;
}

void Removed::setRegionToNull() noexcept {
    region_.reset();
    dirtyFlag_[3] = true;
}

const std::string &Removed::getValueOfAvatar() const noexcept {
    const static std::string defaultValue = std::string();
    if (avatar_)
        return *avatar_;
    return defaultValue;
}

const std::shared_ptr<std::string> &Removed::getAvatar() const noexcept {
    return avatar_;
}

void Removed::setAvatar(const std::string &pAvatar) noexcept {
    avatar_ = std::make_shared<std::string>(pAvatar);
    dirtyFlag_[4] = true;
}

void Removed::setAvatar(std::string &&pAvatar) noexcept {
    avatar_ = std::make_shared<std::string>(std::move(pAvatar));
    dirtyFlag_[4] = true;
}

void Removed::setAvatarToNull() noexcept {
    avatar_.reset();
    dirtyFlag_[4] = true;
}

const std::string &Removed::getValueOfAvatarHash() const noexcept {
    const static std::string defaultValue = std::string();
    if (avatarHash_)
        return *avatarHash_;
    return defaultValue;
}

const std::shared_ptr<std::string> &Removed::getAvatarHash() const noexcept {
    return avatarHash_;
}

void Removed::setAvatarHash(const std::string &pAvatarHash) noexcept {
    avatarHash_ = std::make_shared<std::string>(pAvatarHash);
    dirtyFlag_[5] = true;
}

void Removed::setAvatarHash(std::string &&pAvatarHash) noexcept {
    avatarHash_ = std::make_shared<std::string>(std::move(pAvatarHash));
    dirtyFlag_[5] = true;
}

void Removed::setAvatarHashToNull() noexcept {
    avatarHash_.reset();
    dirtyFlag_[5] = true;
}

const int32_t &Removed::getValueOfAvatarFrame() const noexcept {
    const static int32_t defaultValue = int32_t();
    if (avatarFrame_)
        return *avatarFrame_;
    return defaultValue;
}

const std::shared_ptr<int32_t> &Removed::getAvatarFrame() const noexcept {
    return avatarFrame_;
}

void Removed::setAvatarFrame(const int32_t &pAvatarFrame) noexcept {
    avatarFrame_ = std::make_shared<int32_t>(pAvatarFrame);
    dirtyFlag_[6] = true;
}

void Removed::setAvatarFrameToNull() noexcept {
    avatarFrame_.reset();
    dirtyFlag_[6] = true;
}

const std::string &Removed::getValueOfClan() const noexcept {
    const static std::string defaultValue = std::string();
    if (clan_)
        return *clan_;
    return defaultValue;
}

const std::shared_ptr<std::string> &Removed::getClan() const noexcept {
    return clan_;
}

void Removed::setClan(const std::string &pClan) noexcept {
    clan_ = std::make_shared<std::string>(pClan);
    dirtyFlag_[7] = true;
}

void Removed::setClan(std::string &&pClan) noexcept {
    clan_ = std::make_shared<std::string>(std::move(pClan));
    dirtyFlag_[7] = true;
}

void Removed::setClanToNull() noexcept {
    clan_.reset();
    dirtyFlag_[7] = true;
}

const std::string &Removed::getValueOfPermission() const noexcept {
    const static std::string defaultValue = std::string();
    if (permission_)
        return *permission_;
    return defaultValue;
}

const std::shared_ptr<std::string> &Removed::getPermission() const noexcept {
    return permission_;
}

void Removed::setPermission(const std::string &pPermission) noexcept {
    permission_ = std::make_shared<std::string>(pPermission);
    dirtyFlag_[8] = true;
}

void Removed::setPermission(std::string &&pPermission) noexcept {
    permission_ = std::make_shared<std::string>(std::move(pPermission));
    dirtyFlag_[8] = true;
}

void Removed::setPermissionToNull() noexcept {
    permission_.reset();
    dirtyFlag_[8] = true;
}

const std::string &Removed::getValueOfPassword() const noexcept {
    const static std::string defaultValue = std::string();
    if (password_)
        return *password_;
    return defaultValue;
}

const std::shared_ptr<std::string> &Removed::getPassword() const noexcept {
    return password_;
}

void Removed::setPassword(const std::string &pPassword) noexcept {
    password_ = std::make_shared<std::string>(pPassword);
    dirtyFlag_[9] = true;
}

void Removed::setPassword(std::string &&pPassword) noexcept {
    password_ = std::make_shared<std::string>(std::move(pPassword));
    dirtyFlag_[9] = true;
}

void Removed::setPasswordToNull() noexcept {
    password_.reset();
    dirtyFlag_[9] = true;
}

const std::string &Removed::getValueOfEmail() const noexcept {
    const static std::string defaultValue = std::string();
    if (email_)
        return *email_;
    return defaultValue;
}

const std::shared_ptr<std::string> &Removed::getEmail() const noexcept {
    return email_;
}

void Removed::setEmail(const std::string &pEmail) noexcept {
    email_ = std::make_shared<std::string>(pEmail);
    dirtyFlag_[10] = true;
}

void Removed::setEmail(std::string &&pEmail) noexcept {
    email_ = std::make_shared<std::string>(std::move(pEmail));
    dirtyFlag_[10] = true;
}

void Removed::setEmailToNull() noexcept {
    email_.reset();
    dirtyFlag_[10] = true;
}

const std::string &Removed::getValueOfData() const noexcept {
    const static std::string defaultValue = std::string();
    if (data_)
        return *data_;
    return defaultValue;
}

const std::shared_ptr<std::string> &Removed::getData() const noexcept {
    return data_;
}

void Removed::setData(const std::string &pData) noexcept {
    data_ = std::make_shared<std::string>(pData);
    dirtyFlag_[11] = true;
}

void Removed::setData(std::string &&pData) noexcept {
    data_ = std::make_shared<std::string>(std::move(pData));
    dirtyFlag_[11] = true;
}

const ::trantor::Date &Removed::getValueOfTimestamp() const noexcept {
    const static ::trantor::Date defaultValue = ::trantor::Date();
    if (timestamp_)
        return *timestamp_;
    return defaultValue;
}

const std::shared_ptr<::trantor::Date> &Removed::getTimestamp() const noexcept {
    return timestamp_;
}

void Removed::setTimestamp(const ::trantor::Date &pTimestamp) noexcept {
    timestamp_ = std::make_shared<::trantor::Date>(pTimestamp);
    dirtyFlag_[12] = true;
}

const bool &Removed::getValueOfRecoverable() const noexcept {
    const static bool defaultValue = bool();
    if (recoverable_)
        return *recoverable_;
    return defaultValue;
}

const std::shared_ptr<bool> &Removed::getRecoverable() const noexcept {
    return recoverable_;
}

void Removed::setRecoverable(const bool &pRecoverable) noexcept {
    recoverable_ = std::make_shared<bool>(pRecoverable);
    dirtyFlag_[13] = true;
}

void Removed::updateId(const uint64_t id) {
}

const std::vector<std::string> &Removed::insertColumns() noexcept {
    static const std::vector<std::string> inCols = {
            "id",
            "username",
            "motto",
            "region",
            "avatar",
            "avatar_hash",
            "avatar_frame",
            "clan",
            "permission",
            "password",
            "email",
            "data",
            "timestamp",
            "recoverable"
    };
    return inCols;
}

void Removed::outputArgs(drogon::orm::internal::SqlBinder &binder) const {
    if (dirtyFlag_[0]) {
        if (getId()) {
            binder << getValueOfId();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[1]) {
        if (getUsername()) {
            binder << getValueOfUsername();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[2]) {
        if (getMotto()) {
            binder << getValueOfMotto();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[3]) {
        if (getRegion()) {
            binder << getValueOfRegion();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[4]) {
        if (getAvatar()) {
            binder << getValueOfAvatar();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[5]) {
        if (getAvatarHash()) {
            binder << getValueOfAvatarHash();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[6]) {
        if (getAvatarFrame()) {
            binder << getValueOfAvatarFrame();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[7]) {
        if (getClan()) {
            binder << getValueOfClan();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[8]) {
        if (getPermission()) {
            binder << getValueOfPermission();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[9]) {
        if (getPassword()) {
            binder << getValueOfPassword();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[10]) {
        if (getEmail()) {
            binder << getValueOfEmail();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[11]) {
        if (getData()) {
            binder << getValueOfData();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[12]) {
        if (getTimestamp()) {
            binder << getValueOfTimestamp();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[13]) {
        if (getRecoverable()) {
            binder << getValueOfRecoverable();
        } else {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Removed::updateColumns() const {
    std::vector<std::string> ret;
    if (dirtyFlag_[0]) {
        ret.push_back(getColumnName(0));
    }
    if (dirtyFlag_[1]) {
        ret.push_back(getColumnName(1));
    }
    if (dirtyFlag_[2]) {
        ret.push_back(getColumnName(2));
    }
    if (dirtyFlag_[3]) {
        ret.push_back(getColumnName(3));
    }
    if (dirtyFlag_[4]) {
        ret.push_back(getColumnName(4));
    }
    if (dirtyFlag_[5]) {
        ret.push_back(getColumnName(5));
    }
    if (dirtyFlag_[6]) {
        ret.push_back(getColumnName(6));
    }
    if (dirtyFlag_[7]) {
        ret.push_back(getColumnName(7));
    }
    if (dirtyFlag_[8]) {
        ret.push_back(getColumnName(8));
    }
    if (dirtyFlag_[9]) {
        ret.push_back(getColumnName(9));
    }
    if (dirtyFlag_[10]) {
        ret.push_back(getColumnName(10));
    }
    if (dirtyFlag_[11]) {
        ret.push_back(getColumnName(11));
    }
    if (dirtyFlag_[12]) {
        ret.push_back(getColumnName(12));
    }
    if (dirtyFlag_[13]) {
        ret.push_back(getColumnName(13));
    }
    return ret;
}

void Removed::updateArgs(drogon::orm::internal::SqlBinder &binder) const {
    if (dirtyFlag_[0]) {
        if (getId()) {
            binder << getValueOfId();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[1]) {
        if (getUsername()) {
            binder << getValueOfUsername();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[2]) {
        if (getMotto()) {
            binder << getValueOfMotto();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[3]) {
        if (getRegion()) {
            binder << getValueOfRegion();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[4]) {
        if (getAvatar()) {
            binder << getValueOfAvatar();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[5]) {
        if (getAvatarHash()) {
            binder << getValueOfAvatarHash();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[6]) {
        if (getAvatarFrame()) {
            binder << getValueOfAvatarFrame();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[7]) {
        if (getClan()) {
            binder << getValueOfClan();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[8]) {
        if (getPermission()) {
            binder << getValueOfPermission();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[9]) {
        if (getPassword()) {
            binder << getValueOfPassword();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[10]) {
        if (getEmail()) {
            binder << getValueOfEmail();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[11]) {
        if (getData()) {
            binder << getValueOfData();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[12]) {
        if (getTimestamp()) {
            binder << getValueOfTimestamp();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[13]) {
        if (getRecoverable()) {
            binder << getValueOfRecoverable();
        } else {
            binder << nullptr;
        }
    }
}

Json::Value Removed::toJson() const {
    Json::Value ret;
    if (getId()) {
        ret["id"] = (Json::Int64) getValueOfId();
    } else {
        ret["id"] = Json::Value();
    }
    if (getUsername()) {
        ret["username"] = getValueOfUsername();
    } else {
        ret["username"] = Json::Value();
    }
    if (getMotto()) {
        ret["motto"] = getValueOfMotto();
    } else {
        ret["motto"] = Json::Value();
    }
    if (getRegion()) {
        ret["region"] = getValueOfRegion();
    } else {
        ret["region"] = Json::Value();
    }
    if (getAvatar()) {
        ret["avatar"] = getValueOfAvatar();
    } else {
        ret["avatar"] = Json::Value();
    }
    if (getAvatarHash()) {
        ret["avatar_hash"] = getValueOfAvatarHash();
    } else {
        ret["avatar_hash"] = Json::Value();
    }
    if (getAvatarFrame()) {
        ret["avatar_frame"] = getValueOfAvatarFrame();
    } else {
        ret["avatar_frame"] = Json::Value();
    }
    if (getClan()) {
        ret["clan"] = getValueOfClan();
    } else {
        ret["clan"] = Json::Value();
    }
    if (getPermission()) {
        ret["permission"] = getValueOfPermission();
    } else {
        ret["permission"] = Json::Value();
    }
    if (getPassword()) {
        ret["password"] = getValueOfPassword();
    } else {
        ret["password"] = Json::Value();
    }
    if (getEmail()) {
        ret["email"] = getValueOfEmail();
    } else {
        ret["email"] = Json::Value();
    }
    if (getData()) {
        ret["data"] = getValueOfData();
    } else {
        ret["data"] = Json::Value();
    }
    if (getTimestamp()) {
        ret["timestamp"] = getTimestamp()->toDbStringLocal();
    } else {
        ret["timestamp"] = Json::Value();
    }
    if (getRecoverable()) {
        ret["recoverable"] = getValueOfRecoverable();
    } else {
        ret["recoverable"] = Json::Value();
    }
    return ret;
}

Json::Value Removed::toMasqueradedJson(
        const std::vector<std::string> &pMasqueradingVector) const {
    Json::Value ret;
    if (pMasqueradingVector.size() == 14) {
        if (!pMasqueradingVector[0].empty()) {
            if (getId()) {
                ret[pMasqueradingVector[0]] = (Json::Int64) getValueOfId();
            } else {
                ret[pMasqueradingVector[0]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[1].empty()) {
            if (getUsername()) {
                ret[pMasqueradingVector[1]] = getValueOfUsername();
            } else {
                ret[pMasqueradingVector[1]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[2].empty()) {
            if (getMotto()) {
                ret[pMasqueradingVector[2]] = getValueOfMotto();
            } else {
                ret[pMasqueradingVector[2]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[3].empty()) {
            if (getRegion()) {
                ret[pMasqueradingVector[3]] = getValueOfRegion();
            } else {
                ret[pMasqueradingVector[3]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[4].empty()) {
            if (getAvatar()) {
                ret[pMasqueradingVector[4]] = getValueOfAvatar();
            } else {
                ret[pMasqueradingVector[4]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[5].empty()) {
            if (getAvatarHash()) {
                ret[pMasqueradingVector[5]] = getValueOfAvatarHash();
            } else {
                ret[pMasqueradingVector[5]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[6].empty()) {
            if (getAvatarFrame()) {
                ret[pMasqueradingVector[6]] = getValueOfAvatarFrame();
            } else {
                ret[pMasqueradingVector[6]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[7].empty()) {
            if (getClan()) {
                ret[pMasqueradingVector[7]] = getValueOfClan();
            } else {
                ret[pMasqueradingVector[7]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[8].empty()) {
            if (getPermission()) {
                ret[pMasqueradingVector[8]] = getValueOfPermission();
            } else {
                ret[pMasqueradingVector[8]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[9].empty()) {
            if (getPassword()) {
                ret[pMasqueradingVector[9]] = getValueOfPassword();
            } else {
                ret[pMasqueradingVector[9]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[10].empty()) {
            if (getEmail()) {
                ret[pMasqueradingVector[10]] = getValueOfEmail();
            } else {
                ret[pMasqueradingVector[10]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[11].empty()) {
            if (getData()) {
                ret[pMasqueradingVector[11]] = getValueOfData();
            } else {
                ret[pMasqueradingVector[11]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[12].empty()) {
            if (getTimestamp()) {
                ret[pMasqueradingVector[12]] = getTimestamp()->toDbStringLocal();
            } else {
                ret[pMasqueradingVector[12]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[13].empty()) {
            if (getRecoverable()) {
                ret[pMasqueradingVector[13]] = getValueOfRecoverable();
            } else {
                ret[pMasqueradingVector[13]] = Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if (getId()) {
        ret["id"] = (Json::Int64) getValueOfId();
    } else {
        ret["id"] = Json::Value();
    }
    if (getUsername()) {
        ret["username"] = getValueOfUsername();
    } else {
        ret["username"] = Json::Value();
    }
    if (getMotto()) {
        ret["motto"] = getValueOfMotto();
    } else {
        ret["motto"] = Json::Value();
    }
    if (getRegion()) {
        ret["region"] = getValueOfRegion();
    } else {
        ret["region"] = Json::Value();
    }
    if (getAvatar()) {
        ret["avatar"] = getValueOfAvatar();
    } else {
        ret["avatar"] = Json::Value();
    }
    if (getAvatarHash()) {
        ret["avatar_hash"] = getValueOfAvatarHash();
    } else {
        ret["avatar_hash"] = Json::Value();
    }
    if (getAvatarFrame()) {
        ret["avatar_frame"] = getValueOfAvatarFrame();
    } else {
        ret["avatar_frame"] = Json::Value();
    }
    if (getClan()) {
        ret["clan"] = getValueOfClan();
    } else {
        ret["clan"] = Json::Value();
    }
    if (getPermission()) {
        ret["permission"] = getValueOfPermission();
    } else {
        ret["permission"] = Json::Value();
    }
    if (getPassword()) {
        ret["password"] = getValueOfPassword();
    } else {
        ret["password"] = Json::Value();
    }
    if (getEmail()) {
        ret["email"] = getValueOfEmail();
    } else {
        ret["email"] = Json::Value();
    }
    if (getData()) {
        ret["data"] = getValueOfData();
    } else {
        ret["data"] = Json::Value();
    }
    if (getTimestamp()) {
        ret["timestamp"] = getTimestamp()->toDbStringLocal();
    } else {
        ret["timestamp"] = Json::Value();
    }
    if (getRecoverable()) {
        ret["recoverable"] = getValueOfRecoverable();
    } else {
        ret["recoverable"] = Json::Value();
    }
    return ret;
}

bool Removed::validateJsonForCreation(const Json::Value &pJson, std::string &err) {
    if (pJson.isMember("id")) {
        if (!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    } else {
        err = "The id column cannot be null";
        return false;
    }
    if (pJson.isMember("username")) {
        if (!validJsonOfField(1, "username", pJson["username"], err, true))
            return false;
    }
    if (pJson.isMember("motto")) {
        if (!validJsonOfField(2, "motto", pJson["motto"], err, true))
            return false;
    }
    if (pJson.isMember("region")) {
        if (!validJsonOfField(3, "region", pJson["region"], err, true))
            return false;
    }
    if (pJson.isMember("avatar")) {
        if (!validJsonOfField(4, "avatar", pJson["avatar"], err, true))
            return false;
    }
    if (pJson.isMember("avatar_hash")) {
        if (!validJsonOfField(5, "avatar_hash", pJson["avatar_hash"], err, true))
            return false;
    }
    if (pJson.isMember("avatar_frame")) {
        if (!validJsonOfField(6, "avatar_frame", pJson["avatar_frame"], err, true))
            return false;
    }
    if (pJson.isMember("clan")) {
        if (!validJsonOfField(7, "clan", pJson["clan"], err, true))
            return false;
    }
    if (pJson.isMember("permission")) {
        if (!validJsonOfField(8, "permission", pJson["permission"], err, true))
            return false;
    }
    if (pJson.isMember("password")) {
        if (!validJsonOfField(9, "password", pJson["password"], err, true))
            return false;
    }
    if (pJson.isMember("email")) {
        if (!validJsonOfField(10, "email", pJson["email"], err, true))
            return false;
    }
    if (pJson.isMember("data")) {
        if (!validJsonOfField(11, "data", pJson["data"], err, true))
            return false;
    }
    if (pJson.isMember("timestamp")) {
        if (!validJsonOfField(12, "timestamp", pJson["timestamp"], err, true))
            return false;
    }
    if (pJson.isMember("recoverable")) {
        if (!validJsonOfField(13, "recoverable", pJson["recoverable"], err, true))
            return false;
    }
    return true;
}

bool Removed::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err) {
    if (pMasqueradingVector.size() != 14) {
        err = "Bad masquerading vector";
        return false;
    }
    try {
        if (!pMasqueradingVector[0].empty()) {
            if (pJson.isMember(pMasqueradingVector[0])) {
                if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                    return false;
            } else {
                err = "The " + pMasqueradingVector[0] + " column cannot be null";
                return false;
            }
        }
        if (!pMasqueradingVector[1].empty()) {
            if (pJson.isMember(pMasqueradingVector[1])) {
                if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                    return false;
            }
        }
        if (!pMasqueradingVector[2].empty()) {
            if (pJson.isMember(pMasqueradingVector[2])) {
                if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                    return false;
            }
        }
        if (!pMasqueradingVector[3].empty()) {
            if (pJson.isMember(pMasqueradingVector[3])) {
                if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                    return false;
            }
        }
        if (!pMasqueradingVector[4].empty()) {
            if (pJson.isMember(pMasqueradingVector[4])) {
                if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                    return false;
            }
        }
        if (!pMasqueradingVector[5].empty()) {
            if (pJson.isMember(pMasqueradingVector[5])) {
                if (!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                    return false;
            }
        }
        if (!pMasqueradingVector[6].empty()) {
            if (pJson.isMember(pMasqueradingVector[6])) {
                if (!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                    return false;
            }
        }
        if (!pMasqueradingVector[7].empty()) {
            if (pJson.isMember(pMasqueradingVector[7])) {
                if (!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                    return false;
            }
        }
        if (!pMasqueradingVector[8].empty()) {
            if (pJson.isMember(pMasqueradingVector[8])) {
                if (!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                    return false;
            }
        }
        if (!pMasqueradingVector[9].empty()) {
            if (pJson.isMember(pMasqueradingVector[9])) {
                if (!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                    return false;
            }
        }
        if (!pMasqueradingVector[10].empty()) {
            if (pJson.isMember(pMasqueradingVector[10])) {
                if (!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                    return false;
            }
        }
        if (!pMasqueradingVector[11].empty()) {
            if (pJson.isMember(pMasqueradingVector[11])) {
                if (!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                    return false;
            }
        }
        if (!pMasqueradingVector[12].empty()) {
            if (pJson.isMember(pMasqueradingVector[12])) {
                if (!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                    return false;
            }
        }
        if (!pMasqueradingVector[13].empty()) {
            if (pJson.isMember(pMasqueradingVector[13])) {
                if (!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, true))
                    return false;
            }
        }
    }
    catch (const Json::LogicError &e) {
        err = e.what();
        return false;
    }
    return true;
}

bool Removed::validateJsonForUpdate(const Json::Value &pJson, std::string &err) {
    if (pJson.isMember("id")) {
        if (!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    } else {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if (pJson.isMember("username")) {
        if (!validJsonOfField(1, "username", pJson["username"], err, false))
            return false;
    }
    if (pJson.isMember("motto")) {
        if (!validJsonOfField(2, "motto", pJson["motto"], err, false))
            return false;
    }
    if (pJson.isMember("region")) {
        if (!validJsonOfField(3, "region", pJson["region"], err, false))
            return false;
    }
    if (pJson.isMember("avatar")) {
        if (!validJsonOfField(4, "avatar", pJson["avatar"], err, false))
            return false;
    }
    if (pJson.isMember("avatar_hash")) {
        if (!validJsonOfField(5, "avatar_hash", pJson["avatar_hash"], err, false))
            return false;
    }
    if (pJson.isMember("avatar_frame")) {
        if (!validJsonOfField(6, "avatar_frame", pJson["avatar_frame"], err, false))
            return false;
    }
    if (pJson.isMember("clan")) {
        if (!validJsonOfField(7, "clan", pJson["clan"], err, false))
            return false;
    }
    if (pJson.isMember("permission")) {
        if (!validJsonOfField(8, "permission", pJson["permission"], err, false))
            return false;
    }
    if (pJson.isMember("password")) {
        if (!validJsonOfField(9, "password", pJson["password"], err, false))
            return false;
    }
    if (pJson.isMember("email")) {
        if (!validJsonOfField(10, "email", pJson["email"], err, false))
            return false;
    }
    if (pJson.isMember("data")) {
        if (!validJsonOfField(11, "data", pJson["data"], err, false))
            return false;
    }
    if (pJson.isMember("timestamp")) {
        if (!validJsonOfField(12, "timestamp", pJson["timestamp"], err, false))
            return false;
    }
    if (pJson.isMember("recoverable")) {
        if (!validJsonOfField(13, "recoverable", pJson["recoverable"], err, false))
            return false;
    }
    return true;
}

bool Removed::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err) {
    if (pMasqueradingVector.size() != 14) {
        err = "Bad masquerading vector";
        return false;
    }
    try {
        if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
            if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
                return false;
        } else {
            err = "The value of primary key must be set in the json object for update";
            return false;
        }
        if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
            if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
                return false;
        }
        if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
            if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
                return false;
        }
        if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
            if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
                return false;
        }
        if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
            if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
                return false;
        }
        if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5])) {
            if (!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
                return false;
        }
        if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6])) {
            if (!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
                return false;
        }
        if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7])) {
            if (!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
                return false;
        }
        if (!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8])) {
            if (!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
                return false;
        }
        if (!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9])) {
            if (!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
                return false;
        }
        if (!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10])) {
            if (!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
                return false;
        }
        if (!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11])) {
            if (!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
                return false;
        }
        if (!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12])) {
            if (!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
                return false;
        }
        if (!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13])) {
            if (!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, false))
                return false;
        }
    }
    catch (const Json::LogicError &e) {
        err = e.what();
        return false;
    }
    return true;
}

bool Removed::validJsonOfField(size_t index,
                               const std::string &fieldName,
                               const Json::Value &pJson,
                               std::string &err,
                               bool isForCreation) {
    switch (index) {
        case 0:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isInt64()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 1:
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 2:
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 3:
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isInt()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 4:
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 5:
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 6:
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isInt()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 7:
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 8:
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 9:
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 10:
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 11:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 12:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 13:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isBool()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        default:
            err = "Internal error in the server";
            return false;
            break;
    }
    return true;
}
